name: Check and Build Files

on:
  # Trigger the workflow on push or pull request,
  # but not for the master and gh-pages branches
  push:
    branches-ignore:
      - 'gh-pages'
      - 'master'
    paths:
      - '**.rst'
      - '**.txt'
      - '**/images/*'
      - '_static/**'
      - '_templates/**'
      - '.github/workflows/test.yml'
      - 'setup.py'
      - 'conf.py'
  pull_request:
    branches:
      - 'master'
    paths:
      - '**.rst'
      - '**.txt'
      - '**/images/*'
      - '_static/**'
      - '_templates/**'
      - '.github/workflows/test.yml'
      - 'setup.py'
      - 'conf.py'

jobs:
  lint_rst:
    name: Check with LintRST
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test RST Files
      run: python ./setup.py test rst

  build_files:
    name: Build output files
    needs: lint_rst
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo sphinx-build found at: `which sphinx-build`
        echo sphinx-intl found at: `which sphinx-intl`
        export SPHINXBUILD=`which sphinx-build`
        mkdir _build
        mkdir docs
    - name: Build HTML Files
      run: |
        python ./setup.py -l all build html
    - name: Install LaTeX dependencies
      run: |
        sudo apt-get install latexmk xzdec texlive texlive-latex-extra texlive-lang-french texlive-lang-german texlive-lang-european texlive-lang-spanish
    - name: List Language Packages
      run: |
        apt-cache search texlive-lang-
    - name: Build PDF Files
      run: |
        echo python ./setup.py -l all build pdf
        sphinx-build -M latexpdf . _build -c . -D language=fr
    - name: Build EPUB Files
      run: |
        python ./setup.py -l all build epub
    - name: Display Output Directory
      run: |
        ls -al docs
